"""Extract canonical TOML from per-agent MCP JSON config files (FR-028).

Lifted from twmcp/extractor.py — purely textual transformation, no dep on
twagent.config types. Output goes to stdout via the CLI verb.
"""

import json
from pathlib import Path

_KNOWN_PROPS = frozenset({"command", "args", "type", "env", "url", "headers", "tools"})
_SECRET_SUFFIXES = ("_token", "_key", "_secret", "_password", "_credentials")
_TYPE_MAP = {"local": "stdio"}


def detect_servers(data: dict) -> dict[str, dict]:
    servers = None
    if "mcpServers" in data:
        servers = data["mcpServers"]
    elif "mcp" in data and isinstance(data["mcp"], dict):
        servers = data["mcp"].get("servers")
    elif "servers" in data:
        servers = data["servers"]
    if not servers:
        raise ValueError(
            "No MCP servers found\n"
            '  Expected one of: "mcpServers", "mcp.servers", or "servers" key'
        )
    return servers


def is_secret_key(key: str) -> bool:
    lower = key.lower().replace("-", "_")
    return any(lower.endswith(suffix) for suffix in _SECRET_SUFFIXES)


def normalize_type(server_type: str) -> str:
    return _TYPE_MAP.get(server_type, server_type)


def _format_toml_value(value: object) -> str:
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        items = ", ".join(_format_toml_value(item) for item in value)
        return f"[{items}]"
    return f'"{value}"'


def format_server_toml(
    name: str,
    server: dict,
    *,
    return_secrets: bool = False,
) -> str | tuple[str, set[str]]:
    lines: list[str] = []
    secrets: set[str] = set()
    lines.append(f"[servers.{name}]")
    server_type = server.get("type", "stdio")
    canonical_type = normalize_type(server_type)
    if "command" in server:
        lines.append(f"command = {_format_toml_value(server['command'])}")
    if "args" in server:
        lines.append(f"args = {_format_toml_value(server['args'])}")
    lines.append(f'type = "{canonical_type}"')
    if "url" in server:
        lines.append(f"url = {_format_toml_value(server['url'])}")
    if "tools" in server:
        lines.append(f"tools = {_format_toml_value(server['tools'])}")
    for key, value in server.items():
        if key not in _KNOWN_PROPS:
            lines.append(f"# unknown: {key} = {json.dumps(value)}")
    env = server.get("env")
    if env:
        lines.append("")
        lines.append(f"[servers.{name}.env]")
        for k, v in env.items():
            if is_secret_key(k):
                secrets.add(k)
                lines.append(f'{k} = "${{{k}}}"')
            else:
                lines.append(f"{k} = {_format_toml_value(v)}")
    headers = server.get("headers")
    if headers:
        lines.append("")
        lines.append(f"[servers.{name}.headers]")
        for k, v in headers.items():
            if is_secret_key(k):
                secrets.add(k)
                lines.append(f'{k} = "${{{k}}}"')
            else:
                lines.append(f"{k} = {_format_toml_value(v)}")
    toml_str = "\n".join(lines)
    if return_secrets:
        return toml_str, secrets
    return toml_str


def servers_to_toml(servers: dict[str, dict], *, source: str = "") -> str:
    all_secrets: set[str] = set()
    blocks: list[str] = []
    for name, server_data in servers.items():
        block, secrets = format_server_toml(name, server_data, return_secrets=True)
        blocks.append(block)
        all_secrets.update(secrets)
    header = [f"# Generated by: twagent extract {source}"]
    if all_secrets:
        var_list = ", ".join(sorted(all_secrets))
        header.append("# Secret placeholders (set these environment variables):")
        header.append(f"#   {var_list}")
    parts = ["\n".join(header), *blocks]
    return "\n\n".join(parts) + "\n"


def extract_from_file(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")
    text = path.read_text()
    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON: {path}\n  {e}") from e
    servers = detect_servers(data)
    return servers_to_toml(servers, source=str(path))
